name: Project CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

    types: [closed]
    
    
jobs:
  get_version_info:
    name: Check current version

    # if: github.event.pull_request.merged == true

    uses: ./.github/workflows/check-version.yml
    with:
      version-file: ./pyproject.toml
      curr-version: True


  get_release_info:
    name: Fetch last release
    runs-on: ubuntu-latest

    needs: [get_version_info]

    outputs:
      release_id: ${{ steps.get_release.outputs.release_id }}
      release_name: ${{ steps.get_release.outputs.release_name }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch release
        id: get_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          latest_release_json=$(gh release view --json id,name)
          release_id=$(echo "$latest_release_json" | jq -r '.id')
          release_name=$(echo "$latest_release_json" | jq -r '.name')
          echo "release_id=$release_id" >> $GITHUB_OUTPUT
          echo "release_name=$release_name" >> $GITHUB_OUTPUT

    
  compare_versions:
    name: Deploy
    
    needs: [get_version_info, get_release_info]

    if: ${{ needs.get_version_info.outputs.release_version != needs.get_release_info.outputs.release_name }}

    uses: ./.github/workflows/publish.yml
    with:
      release: ${{ needs.get_version_info.outputs.release_version }}
      prerelease: ${{ fromJSON(needs.get_version_info.outputs.is_prerelease) }}
