name: Testing provisional
on: [workflow_dispatch]

jobs:
  call-workflow-passing-new:
    name: another name needed (1)
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    uses: ./.github/workflows/check-version.yml
    with:
      version-file: ./pyproject.toml
      curr-version: True

  call-workflow-passing-old:
    name: another name needed (2)
    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    uses: ./.github/workflows/check-version.yml
    with:
      version-file: ./pyproject.toml
      curr-version: False
    
  final-in-flow:
    name: Final call
    runs-on: ubuntu-latest
    
    needs: [call-workflow-passing-new, call-workflow-passing-old]
     
    steps:   
      - run: echo ${{ needs.call-workflow-passing-new.outputs.release_version }} ${{ needs.call-workflow-passing-new.outputs.is_prerelease }}
      - run: echo ${{ needs.call-workflow-passing-old.outputs.release_version }} ${{ needs.call-workflow-passing-old.outputs.is_prerelease }}
      
      - name: Check in final call
        if: ${{ needs.call-workflow-passing-new.outputs.release_version == needs.call-workflow-passing-old.outputs.release_version }}
        run: echo "Versions are equal"
        
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Better test, Get latest release name
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          latest_release_json=$(gh release view --json id,name)
           echo "$latest_release_json"
           release_id=$(echo "$latest_release_json" | jq -r '.id')
           release_name=$(echo "$latest_release_json" | jq -r '.name')
           echo "release_id=$release_id" >> $GITHUB_ENV
           echo "release_name=$release_name" >> $GITHUB_ENV

            
      - name: Print result
        run: |
          echo "id: ${{ env.release_name }}"
          echo "name: ${{ env.release_id }}"

      - name: Better test, get a comparison
        if: ${{ needs.call-workflow-passing-new.outputs.release_version == env.release_name }}
        run: echo "Releases are equal"
        